---
  dataset: "cifar10"
  # Learner parameters
  num_ff_layers: 0
  num_epoch: 10
  num_subepoch: 5
  batch_size: 64
  optim: "Adam"
  learning_rate: 1E-3
  weight_decay: 1E-3
  validation_split_ratio: 0.16666667
  # Backdoor set parameters
  targ_idx: 1500
  # Change prediction from targ_cls -> pois_cls
  targ_cls: 1
  pois_cls: 5
  backdoor_cnt: 150
  backdoor_attack: "four-pixel"
  backdoor_delta: 2.0
  # influence function parameters
  hvp_batch_size: 1
  damp: 1E-2
  scale: 3E7
  r_depth: 1000
  t_repeats: 10
